version: '3'
services:
  db:
    image: mongo:5.0.2
    container_name: db
    restart: always
    ports:
      - 27019:27019
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db
